### ISSUE TITLE
Missing Launchers

### ISSUE THREAD

**Issue by ghost** [iaslab-unipd/rgbd_calibration#4]
According to your instructions, `kinect_data_collection.launch` and `kinect_offline_calibration.launch` shall be there, but they are missing!
I can assume `kinect_47A_tro.launch` to be equivalent to `kinect_offline_calibration.launch`, but then, where is `kinect_data_collection.launch` that is supposed to collect the frames from both RGB and Depth cameras?

**Comment by bassofil** [comment]
@Sahloul You are right: `kinect_47A_tro.launch` is an up-to-date version of `kinect_offline_calibration.launch`.
For what concerns the data acquisition launch file I think I removed it because I ended up using [this package](https://github.com/iaslab-unipd/sensor_data_collection). It is also better documented. I'll modify the `README` as soon as possible.
